version: '3.7'

services:
    redis:
        image: redis
    app:
        container_name: app
        build: .
        volumes:
            - .:/app
        ports:
            - 5000:5000
        depends_on:
            - redis
        links:
            - redis
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
          - app
